// Code generated by "esc -prefix static -o static.go static"; DO NOT EDIT.

package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/.index.html.swp": {
		local:   "static/.index.html.swp",
		size:    12288,
		modtime: 1508978632,
		compressed: `
H4sIAAAAAAAC/+zZv27VMBQG8K/drgQYwQukQbA1LjDQwfcu/JEYEAwtomJyHDcxOMmV7Ra6cFeegwdg
4SXgFdgY2eAN0I0vC1PFVvX7LSc++eIoR8oQpd57+fRZsV/tAcB14Nvu76PX25/xaQU4PeA86qAHe47c
B6cH2dhT62U7yhiMbF3qTurKjL10egi2770Nsh29NH0z1eVJ7Z2Rbmjs+6pLvQcR/Z+ruH/v7vSq3yp3
ips3DjkSIiIiIqJLJC23sAKwvVlf2dStfyoRERERERERXVy6Ab5fA+6I/P//7/f/LwH8FMAPAXwVwBcB
fBTASgDvBPBKAA8EUIl87W3BWRIREREREdFFp2SXer/ATMl6bM4WmM1UNMEtUxGDmZft6Ks3sVwombtT
wOjhVMfCNfPy2FnfrE/n3nqjzT5KdlY3U9674W0RrJ+XMZ15GztrU1l0wR5vOpWJsZyiySVvF+3olcyH
62Zvky5Mp0O0aV4eHjzZ3V+nVb6Byk+gdh49f3hw9OJxkdd/AgAA//8suxLxADAAAA==
`,
	},

	"/gol.js": {
		local:   "static/gol.js",
		size:    4023,
		modtime: 1509199542,
		compressed: `
H4sIAAAAAAAC/7xXX2/bOBJ/lj7FQE9y4shOgLzEdYGm1+v10LsNmgJtEeSBlsYSEVoURDqyGvi7L4YU
JVqxu4tdYF9sav7xx+Fw+OMzq6ESrMVawRJe9ouQJEKmTNxrppGEUEl1Ay+wu4F5Mp9Ca/5hD531iglh
R6ks1zy3Y5XKmtwfYD6FOTxaqUa2eS+FrEkT1ZhFU4hWYotRZ7DmKDJYQibT7QZLneSoPwik4W37KYsj
YxBNFmFoRgnLsg/PWOrPXGkssY6jjdwq3MhnjKZgxndSTRZhw8tMNkfsa1T8Jxnbwb8prIm/LVPNZQkK
9baKaXETeAkDu0pYmuUuwsBziyeLcO95HqjIl5bYwBI6MLwssf7GM10srK4Y6f6DPC90p2Sq+sJ0NzHP
ExPXeMPsQHbg1fDynXNsYAY0FV9DPMjfdpENwqCBs6WbajZ4L8JgDygUGqOCjIYIM+dAVmFgd6YxyJbQ
LJykMLhgSRj8NGU1a4b8pHoHS1sItPvvZalxp+Poym67tWl6k8ZLX1r04sLPwbo5ljWnLEbKg/TlatB+
lEzc85/YqbAeVB+yHL+wjG8VQUz1LlHsGakeQgCgNSW6ZqUSTGM8T67hDNJmCt2omCw6p5QJjFPap3jd
wDlcwRlgPZnCRVoYYTEIJ24qwUv81mXb6rpway7EvW4FHcQorxHLyNN8wVTHFxbCupmCGxZT87keUOla
PmEfqCm4xogmn81Ay21a+GZ/JqrxTLHUWEPK61SgjbDCnJd3TBexm5rVaWy6TvdDoXLVfV4lcziD/zFd
JHefDsHGbpYNz0xBnJqAGsVXaefooTolJdYpx7rRPBWWTOgWVnIXBmtZQ8xhCfMFcHgDVwvg5+f2fJnm
yDPs9orDBVwuwmCcQWNyBq/ySIvvdJ4kpw4X7C2UXDIBBP3vAnE73nftB/7oLA4z6afyFPI4V3Dh1W7g
p/iV0698htSbJY+PwGW3JeYKOnIQXP0aDfWWd4LnJWlsSfqqW6aQYpN2w7NM9I7ufJuPXMgVE+9EVTBK
dnJ1fXCgL011XSZzsv+re7KWJfXOmKLbSoRziKodKFaqqLfiQnylfmlW/8Af+3Jxfia5c5s841Kj0rL2
StkSgg4pQeIZ8NLJLdIjfWElWPp0AOR1AXUxHnj2mHxFtjlVT4aYSOq9vsedVE5Zs2zovnfGxvXfoO8c
lVTJ9ykFSn5MyeVU4+gRx8eKzNyXPINlP+GnzGbhdXG1KIRsTBaOresENFvtvwI4QrjvTzvRrz8q8uN9
lTwppYSjH/+YujXeMiFsSn/VbntIR3qi3Grbhk7dDnABWHt9t/v2bj66MIYbz114XsXuQ8MbGyqVEhv4
hqt7mT6hjqNG3cxmEZw7RkW0lvhGUkil6ezMcilmRCoalchyg0qxnJLniEmMz5YUbRTxvf/e//b/pGK1
QlIkGdOMFq4artMC4o3KE91WaEkiUwiRzWR0EwaBJZFk4/yCVY3saeFsFfFtY7qtMqbxI9ug4eCHTgrL
7HPPz20xWP7kh8xwzbZC33iifbj3Se14ktyNDPzhTeAt2gyVrnmZ83U7eHTHT5kGTYUESxiUt+Z5ELj3
wKC4J8khERwvjqA0KiHxePYXoFzfQGShRlOgFN34b5f9ZETH3Wug31fDDDpBkgqOpf4+heHjxyiAITt+
ADKtaqQHxb9symkfiPGZ1w6Zw9IENGNUD/NHR4crqWIjHWb2P8dz91ir3RSqtqfLNaba58u3cltmvMzf
myjmvE0W/zRrPk2NSUv8Po6rHVwY9InAtZ7QG4Yawjy5ntDNb5qAOfOm/e7gTd8nGtt8KUwvGt4n1vot
vDb2bS2S1l6o13ABcdU6PFpWBk5hgRQHQFoPSGFjtx6Q4hBIOwDxjH3bMBhKNqHrgJDubBGNNOTaUlX8
HgAA//8AQKmPtw8AAA==
`,
	},

	"/index.html": {
		local:   "static/index.html",
		size:    218,
		modtime: 1508978121,
		compressed: `
H4sIAAAAAAAC/yyPvW7DMAyEZ/spVO211g6Ulv6s7eAOGRWJtpTQdiASAfz2gSVPJL7jHXHw9vX7OV7+
vlWShVwPbXSQ0EfXdx0sKF6F5AujWP0//rx/6CpIFkI3bwSmrQekvN5VQbKaZSfkhChapYLTSYbAfPjB
nB/gusW9eoNfn55VjlZPGSlqB6axKnMo+SGKS7B63mi48XHQaA1sQWBahVcAAAD//72LSDzaAAAA
`,
	},

	"/style.css": {
		local:   "static/style.css",
		size:    34,
		modtime: 1509074295,
		compressed: `
H4sIAAAAAAAC/0rKT6lUqObizE0sSs/Ms1IwsObiLEhMScnMSwdzarkAAQAA//8FQun8IgAAAA==
`,
	},

	"/": {
		isDir: true,
		local: "static",
	},
}
