// Code generated by "esc -prefix static -o static.go static"; DO NOT EDIT.

package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/.index.html.swp": {
		local:   "static/.index.html.swp",
		size:    12288,
		modtime: 1508978632,
		compressed: `
H4sIAAAAAAAC/+zZv27VMBQG8K/drgQYwQukQbA1LjDQwfcu/JEYEAwtomJyHDcxOMmV7Ra6cFeegwdg
4SXgFdgY2eAN0I0vC1PFVvX7LSc++eIoR8oQpd57+fRZsV/tAcB14Nvu76PX25/xaQU4PeA86qAHe47c
B6cH2dhT62U7yhiMbF3qTurKjL10egi2770Nsh29NH0z1eVJ7Z2Rbmjs+6pLvQcR/Z+ruH/v7vSq3yp3
ips3DjkSIiIiIqJLJC23sAKwvVlf2dStfyoRERERERERXVy6Ab5fA+6I/P//7/f/LwH8FMAPAXwVwBcB
fBTASgDvBPBKAA8EUIl87W3BWRIREREREdFFp2SXer/ATMl6bM4WmM1UNMEtUxGDmZft6Ks3sVwombtT
wOjhVMfCNfPy2FnfrE/n3nqjzT5KdlY3U9674W0RrJ+XMZ15GztrU1l0wR5vOpWJsZyiySVvF+3olcyH
62Zvky5Mp0O0aV4eHjzZ3V+nVb6Byk+gdh49f3hw9OJxkdd/AgAA//8suxLxADAAAA==
`,
	},

	"/gol.js": {
		local:   "static/gol.js",
		size:    3851,
		modtime: 1509015430,
		compressed: `
H4sIAAAAAAAC/7xXX2/bOBJ/tj7FQE9y4shOgLzEdYGm1+v10LsNmgJtEeSBlsYSEZoURDqyGvi7L4YU
JVpJuotdYF8Sav7+OBwOf35kNVSCtVhrWMHTYRmRRKiMiVvDDJIQKqWv4An2V7BIFzNo7X84QGe9ZkK4
VabkhhdurTNVk/sdLGawgHsnNci275VQNWniGvN4BvFa7DDuDDYcRQ4ryFW226I0aYHmg0BaXref8iS2
BvF0GUV2lbI8//CI0nzm2qDEOom3aqdxqx4xnoFd3yg9XUYNl7lqXrCvUfOfZOwW/6awNv5OZoYrCRrN
rkpoc1N4iiZul7Cy211Gk8AtmS6jQ+B5pCJf2mIDK+jAcCmx/sZzUy6drhzp/oO8KE2nZLr6wkyXmBep
jWu9YX4kO/JquHznHRuYA6XiG0gG+dsuskU4aeBk5VPNB+9lNDkACo3WqCSjIcLcO5BVNHEn01hkK2iW
XlJaXLAiDGGZ8po1Q30ys4eVawQ6/fdKGtybJL5wx+5smt6kCcqXlb24DGuwaV6qmleWI+VR+Qo9aD8q
Jm75T+xUWA+qD3mBX1jOd5ogZmafavaI1A8RANCeUlMzqQUzmCzSSziBrJlBtyqny84pYwKTjM4p2TRw
ChdwAlhPZ3CWlVZYDsKpTyW4xG9dtZ2uC7fhQtyaVtBFjIsaUcaB5gtmJjlzEDbNDPyynNnPzYDK1OoB
+0BNyQ3GlHw+B6N2WRma/Zmo1jNDabCGjNeZQBdhjQWXN8yUiU/N6iyxU6f7Q6EK3X1epAs4gf8xU6Y3
n47BJj7Llue2IV5LQIPiq3I5eqheSYX1yrFulKdCyYRpYa320WSjakg4rGCxBA5v4GIJ/PTU3S87HHmO
3VlxOIPzZTQZV9CanMCzOtLmO10gKWjCTQ4OSqGYAIL+d4H4E++n9h2/9xbHlQxL+RrypNBwFvTuJCzx
M6df+Qylt1seX4Hz7kjsE/TCRfD9azU0W94JXkjSuJYMVddMI8Um7Zbnuegd/f22H4VQaybeiapkVOz0
4vLoQp/b7jpPF2T/V89koyTNzoSiu06EU4irPWgmddxbcSG+0ry0u7/j9327eD9b3IUrnnWpURtVB63s
CEGHlCDxHLj0cof0hbmwFix7OALyvIG6GHc8v0+/Itv+qp/o7of2N0qn32cwFv2Y+SF8YzVuDL82Inps
yWvtNJ9bSvNHjfPyrCJPD7RfDwivmRC/xncE74U5o3bGXe3XJi6cAdbBLOu+g9eEhvDwivhHJOiCQ2S5
WENPn8QGvuH6VmUPaJK40VfzeQynnqUQVaQ3PC2VNtSP80KJOT3UjU6V3KLWrKDi+cc+wUdHNLaaONR/
b3/7f1qxWiMp0pwZRhvXDTdZCclWF6lpK3TEi2mE2FUyvoomE0fMyMb7TdY1soelt9XEYa3prsqZwY9s
i5bXHjtplPnnnvO6xnCcJAyZ44bthLkKRIfoEBLFcZLCryz8gWcHm7ZLbWouC75pB4+ul7UdetRIsIJB
eW0p98Rz7EFxS5JjcjXeHEFpdEricfYnoFpfQeygxjOgEl2FvwcO0xHF9Qy7P1f72naCNBMcpfk+g+Hj
xyiAJRBhADKtaiSS/i9XcjoHYlH2FwSZw8oGtGvUd4t7TzErpRMrHTKHn+PcPdZqP4Oq7SlojZkJOei1
2smcy+K9jWLv23T5TzPR1+kmaYkzJ0m1hzOLPhW4MVP6XUADYZFeTuk1tUPA3nn7E2APb/o50bixTmF6
0cD5nfVbeG4c2jokrXukLuEMkqr1eIyqLJzSASmPgLQBkNLFbgMg5TGQdgASGIe20WRo2bRSOiWke9dE
Iw25ttQVvwcAAP//ogOtkAsPAAA=
`,
	},

	"/index.html": {
		local:   "static/index.html",
		size:    218,
		modtime: 1508978121,
		compressed: `
H4sIAAAAAAAC/yyPvW7DMAyEZ/spVO211g6Ulv6s7eAOGRWJtpTQdiASAfz2gSVPJL7jHXHw9vX7OV7+
vlWShVwPbXSQ0EfXdx0sKF6F5AujWP0//rx/6CpIFkI3bwSmrQekvN5VQbKaZSfkhChapYLTSYbAfPjB
nB/gusW9eoNfn55VjlZPGSlqB6axKnMo+SGKS7B63mi48XHQaA1sQWBahVcAAAD//72LSDzaAAAA
`,
	},

	"/style.css": {
		local:   "static/style.css",
		size:    34,
		modtime: 1509074295,
		compressed: `
H4sIAAAAAAAC/0rKT6lUqObizE0sSs/Ms1IwsObiLEhMScnMSwdzarkAAQAA//8FQun8IgAAAA==
`,
	},

	"/": {
		isDir: true,
		local: "static",
	},
}
